/**
 * Problem 2
 * 19 October 2001
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 * 
 * Answer: 4613732
 */
public class Problem2 {

	public static void main(String[] args) {
		int sum = 0;
		int max = 4000000;
		int prev = 1;
		int next = 2;
		int f = 0;

		while (next < max) {
			f = next;
			next += prev;
			prev = f;
			sum = (f % 2 == 0) ? sum += f : sum;
		}

		System.out.println("Even valued terms in Fibonacci seq below 4 million = " + sum);
	}
}
